eventhor_main_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PugboEventhorBundle:Default:index }

pugbo_eventhor_yard_new:
    pattern: /yards/new
    defaults: { _controller: PugboEventhorBundle:Yard:new }
