parameters:
#    eventhor_main.example.class: Pugbo\Bundle\EventhorBundle\Example

services:
#    eventhor_main.example:
#        class: %eventhor_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
